apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-configuration-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/yas-configuration
    helm:
      values: |
        applicationConfig:
          springdoc:
            oauthflow:
              authorization-url: http://identity.yas.local.com/realms/Yas/protocol/openid-connect/auth
              token-url: http://identity.yas.local.com/realms/Yas/protocol/openid-connect/token
        mediaApplicationConfig:
          yas:
            publicUrl: http://staging-api.yas.local.com/media
        paymentPaypalApplicationConfig:
          yas:
            public:
              url: http://staging-storefront.yas.local.com/complete-payment
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backoffice-bff-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/backoffice-bff
    helm:
      values: |
        backend:
          ingress:
            host: staging-backoffice.yas.local.com
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backoffice-ui-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/backoffice-ui
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storefront-bff-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/storefront-bff
    helm:
      values: |
        backend:
          ingress:
            host: staging-storefront.yas.local.com
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storefront-ui-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/storefront-ui
    helm:
      values: |
        ui:
          extraEnvs:
            - name: API_BASE_PATH
              value: http://staging-storefront.yas.local.com/api
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swagger-ui-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/swagger-ui
    helm:
      values: |
        urls: "[{ url: 'http://staging-api.yas.local.com/product/v3/api-docs', name: 'Product' }, { url: 'http://staging-api.yas.local.com/media/v3/api-docs', name: 'Media' }, { url: 'http://staging-api.yas.local.com/customer/v3/api-docs', name: 'Customer' }, { url: 'http://staging-api.yas.local.com/cart/v3/api-docs', name: 'Cart'}, { url: 'http://staging-api.yas.local.com/rating/v3/api-docs', name: 'Rating' }, { url: 'http://staging-api.yas.local.com/order/v3/api-docs', name: 'Order'}, { url: 'http://staging-api.yas.local.com/payment/v3/api-docs', name: 'Payment'}, { url: 'http://staging-api.yas.local.com/location/v3/api-docs', name: 'Location'}, { url: 'http://staging-api.yas.local.com/inventory/v3/api-docs', name: 'Inventory'}, { url: 'http://staging-api.yas.local.com/tax/v3/api-docs', name: 'Tax' }, { url: 'http://staging-api.yas.local.com/promotion/v3/api-docs', name: 'Promotion'}, { url: 'http://staging-api.yas.local.com/search/v3/api-docs', name: 'Search'}]"
        ingress:
          host: staging-api.yas.local.com
          hosts:
            - host: staging-api.yas.local.com
              paths:
                - path: /swagger-ui
                  pathType: ImplementationSpecific
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cart-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/cart
    helm:
      values: |
        backend:
          databaseName: cart_staging
          databaseConnectionUrl: jdbc:postgresql://postgres.infra:5432
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/customer
    helm:
      values: |
        backend:
          databaseName: customer_staging
          databaseConnectionUrl: jdbc:postgresql://postgres.infra:5432
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/inventory
    helm:
      values: |
        backend:
          databaseName: inventory_staging
          databaseConnectionUrl: jdbc:postgresql://postgres.infra:5432
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: location-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/location
    helm:
      values: |
        backend:
          databaseName: location_staging
          databaseConnectionUrl: jdbc:postgresql://postgres.infra:5432
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/media
    helm:
      values: |
        backend:
          databaseName: media_staging
          databaseConnectionUrl: jdbc:postgresql://postgres.infra:5432
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/order
    helm:
      values: |
        backend:
          databaseName: order_staging
          databaseConnectionUrl: jdbc:postgresql://postgres.infra:5432
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/payment
    helm:
      values: |
        backend:
          databaseName: payment_staging
          databaseConnectionUrl: jdbc:postgresql://postgres.infra:5432
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-paypal-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/payment-paypal
    helm:
      values: |
        backend:
          databaseName: payment_paypal_staging
          databaseConnectionUrl: jdbc:postgresql://postgres.infra:5432
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/product
    helm:
      values: |
        backend:
          databaseName: product_staging
          databaseConnectionUrl: jdbc:postgresql://postgres.infra:5432
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promotion-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/promotion
    helm:
      values: |
        backend:
          databaseName: promotion_staging
          databaseConnectionUrl: jdbc:postgresql://postgres.infra:5432
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rating-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/rating
    helm:
      values: |
        backend:
          databaseName: rating_staging
          databaseConnectionUrl: jdbc:postgresql://postgres.infra:5432
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recommendation-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/recommendation
    helm:
      values: |
        backend:
          databaseName: recommendation_staging
          databaseConnectionUrl: jdbc:postgresql://postgres.infra:5432
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: search-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/search
    helm:
      values: |
        backend:
          databaseName: search_staging
          databaseConnectionUrl: jdbc:postgresql://postgres.infra:5432
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tax-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/tax
    helm:
      values: |
        backend:
          databaseName: tax_staging
          databaseConnectionUrl: jdbc:postgresql://postgres.infra:5432
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webhook-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/webhook
    helm:
      values: |
        backend:
          databaseName: webhook_staging
          databaseConnectionUrl: jdbc:postgresql://postgres.infra:5432
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sampledata-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: charts/sampledata
    helm:
      values: |
        backend:
          databaseName: sampledata_staging
          databaseConnectionUrl: jdbc:postgresql://postgres.infra:5432
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-istio-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-gitops.git'
    targetRevision: HEAD
    path: istio/staging
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
