apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - repoURL: https://github.com/23120049/yas-helm.git
      targetRevision: main
      path: deploy/keycloak/keycloak
      helm:
        valueFiles:
          - $values/values/infra/keycloak.yaml
    - repoURL: https://github.com/23120049/yas-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
