apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23120049/yas-helm.git'
    targetRevision: HEAD
    path: deploy/postgres/pgadmin
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true
