apiVersion: argoproj.io/v1alpha1kind: Applicationmetadata:  name: postgresql  namespace: argocd

  annotations:

    argocd.argoproj.io/sync-wave: "0"
spec:  project: default  sources:    - repoURL: 'https://github.com/23120049/yas-helm.git'      targetRevision: HEAD      path: deploy/postgres/postgresql
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/23120049/yas-helm.git'
      targetRevision: HEAD
      path: deploy/postgres/postgresql
      helm:        valueFiles:          - $values/values/infra/postgres.yaml    - repoURL: 'https://github.com/23120049/yas-gitops.git'      targetRevision: HEAD      ref: values  destination:    server: 'https://kubernetes.default.svc'    namespace: infra
  syncPolicy:    automated:      prune: true      selfHeal: true    syncOptions:
      - CreateNamespace=true