apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: backoffice-bff-dev
  namespace: observability
  labels:
    app.kubernetes.io/instance: backoffice-bff-dev
    app.kubernetes.io/name: backoffice-bff
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: backoffice-bff-dev
      app.kubernetes.io/name: backoffice-bff
  namespaceSelector:
    matchNames:
      - dev
  podMetricsEndpoints:
    - port: metric
      path: /actuator/prometheus
      interval: 30s
      scheme: http
      honorLabels: true
