apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cart-staging
  namespace: observability
  labels:
    app.kubernetes.io/instance: cart-staging
    app.kubernetes.io/name: cart
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: cart-staging
      app.kubernetes.io/name: cart
  namespaceSelector:
    matchNames:
      - staging
  podMetricsEndpoints:
    - port: metric
      path: /actuator/prometheus
      interval: 30s
      scheme: http
      honorLabels: true
