apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: restrict-cart-access
  namespace: yas-staging
spec:
  selector:
    matchLabels:
      app: cart
  action: ALLOW
  rules:
    - from:
        - source:
            # Tam thoi de ten service account nhu du doan. Can verify lai khi app len.
            principals:
              - "cluster.local/ns/yas-staging/sa/storefront-bff"
              - "cluster.local/ns/yas-staging/sa/order"
