elasticsearch:
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
kibana:
  ingress:
    enabled: false
    hostname: kibana.yas.100-108-98-79.sslip.io
