hostname: &hostname grafana.yas.local.com

syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true

grafana:
  adminUser: admin
  adminPassword: admin

  grafana.ini:
    database:
      type: sqlite3
      path: grafana.db

    server:
      domain: grafana.yas.local.com
      root_url: http://grafana.yas.local.com

  ingress:
    ingressClassName: traefik
    enabled: true
    hosts:
      - *hostname
    path: /
    pathType: Prefix

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL
    datasources:
      enabled: true
      label: grafana_datasource
      searchNamespace: ALL

# Additional datasources via ConfigMap ( Tempo + Loki )
grafana dashboards:
  default:
    loki-datasource:
      gnetId: null
      datasourceUid: loki
    tempo-datasource:
      gnetId: null
      datasourceUid: tempo
