hostname: &hostname grafana.yas.local.com

syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true

prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true

grafana:
  adminUser: admin
  adminPassword: admin

  grafana.ini:
    database:
      type: sqlite3
      path: grafana.db

    server:
      domain: grafana.yas.local.com
      root_url: http://grafana.yas.local.com
      
  ingress:
    ingressClassName: 
    enabled: true
    hosts:
      - *hostname
    path: /
    pathType: Prefix
